// Generated by CoffeeScript 1.4.0
var Task, tasks;

tasks = {};

Task = require('./task');

module.exports.task = function(uuid, callback) {
  return callback(tasks[uuid] || (tasks[uuid] = new Task({
    uuid: uuid
  })));
};
