// Generated by CoffeeScript 1.4.0
var Task, tasks;

tasks = {};

Task = require('./task');

module.exports.task = function(opts, callback) {
  var task;
  if ((opts.uuid != null) && (tasks[opts.uuid] != null)) {
    return callback(null, tasks[opts.uuid].reload(opts));
  }
  task = new Task(opts);
  tasks[task.uuid] = task;
  return callback(null, task);
};
