// Generated by CoffeeScript 1.6.3
var testable;

testable = void 0;

module.exports._does = function() {
  return testable;
};

module.exports.does = function(config) {
  var api, local, mode;
  if (config == null) {
    config = {};
  }
  mode = config.mode || 'spec';
  if (mode === 'spec') {
    testable = local = {
      expects: {},
      expect: function() {},
      verify: function() {}
    };
  } else {
    throw new Error("does doesn't " + mode);
  }
  return api = {
    expect: local.expect,
    verify: local.verify
  };
};
