// Generated by CoffeeScript 1.6.3
var entities, id_seq;

id_seq = 0;

entities = {};

Object.defineProperty(Object.prototype, 'does', {
  enumerable: true,
  get: function() {
    return function(opts) {
      var fnName, functions, origFn, _base, _results;
      if (this.$$id == null) {
        this.$$id = ++id_seq;
        entities[this.$$id] = {
          object: this
        };
      }
      _results = [];
      for (fnName in opts) {
        if (fnName === 'does') {
          continue;
        }
        origFn = this[fnName];
        this[fnName] = opts[fnName];
        functions = (_base = entities[this.$$id]).functions || (_base.functions = {});
        _results.push(functions[fnName] = {
          orig: origFn
        });
      }
      return _results;
    };
  }
});

module.exports.entities = entities;
