// Generated by CoffeeScript 1.6.3
var id_seq;

id_seq = 0;

Object.defineProperty(Object.prototype, 'does', {
  enumerable: true,
  get: function() {
    return function(opts) {
      var fnName, _results;
      if (this.$$id == null) {
        this.$$id = ++id_seq;
      }
      _results = [];
      for (fnName in opts) {
        _results.push(this[fnName] = opts[fnName]);
      }
      return _results;
    };
  }
});

module.exports = function() {};
