// Generated by CoffeeScript 1.4.0
var fluent;

fluent = require('./decorators').fluent;

module.exports = {
  create: function(title) {
    var task;
    return task = {
      title: title,
      running: false,
      start: fluent(function() {
        return task.running = true;
      })
    };
  }
};
