// Generated by CoffeeScript 1.4.0
var fluent;

fluent = require('./decorators').fluent;

module.exports = {
  create: function(title) {
    var middleware, task;
    middleware = [];
    task = {
      title: title,
      running: false,
      does: function(actionTitle, actionFn) {
        return middleware.push(actionFn);
      },
      start: fluent(function(input) {
        var fn, _i, _len, _results;
        task.running = true;
        _results = [];
        for (_i = 0, _len = middleware.length; _i < _len; _i++) {
          fn = middleware[_i];
          _results.push(fn(input));
        }
        return _results;
      })
    };
    return task;
  }
};
